name: Update Links and Deploy

on:
  schedule:
    - cron: '*/30 * * * *' # Runs every 30 minutes
  push:
    branches:
      - main

jobs:
  update-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          npm install axios cheerio

      - name: Fetch and Update Links
        run: |
          node index.js
          echo "Content of links.json:"
          cat links.json

      - name: Update Reward Page
        run: |
          echo '<html><body><div class="card shadow-sm mb-2"><div class="card-body"><h2>Wizard of oz slots free coins links:</h2><ul>' > reward.html
          jq -r '.[] | "<li><a href=\"" + .href + "\">" + .text + "</a></li>"' links.json >> reward.html
          echo '</ul></div></div></body></html>' >> reward.html
          echo "Content of reward.html:"
          cat reward.html

      - name: Configure Git
        run: |
          git config --global user.email "prolladmail@gmail.com"
          git config --global user.name "Prollad99"

      - name: Check for Changes
        run: |
          git status
          git diff

      - name: Commit and Push changes
        run: |
          git add reward.html links.json
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update reward links"
            git push https://x-access-token:${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/Prollad99/W-o-Oz.git
          else
            echo "No changes to commit"
          fi